[package]
name = "nullchain-consensus"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
nullchain-types = { path = "../nullchain-types" }
tracing = { workspace = true }
